version: '3'

services:
  db-postgres-powerup:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-powerup"
    restart: always
    volumes:
      - ./banco-de-dados-powerup:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
volumes:
  banco-de-dados-powerup: 
